### ISSUE TITLE
URDF URDF failed Model parse

### ISSUE THREAD

**Issue by wilhem** [benbongalon/ros2-urdf-tutorial#4]
Hi,

thanks for this tutorial

I installed ROS2 - Foxy few days ago.
I downloaded the package from repository, without changing nothing. But I get a URDF issue:
URDF failed Model parse

In RVIZ the axis and the frames are displayed but there is no robot. 

![Bildschirmfoto_2021-07-13_20-58-08](https://user-images.githubusercontent.com/651354/125509894-0de3c7fd-5e82-40be-903c-342fa9aa2ed5.png)

Why?

Thanks

**Comment by benbongalon** [comment]
Hi, the model parsing issue is often due to an unsupported locale. URDF seems to only like en_US. Try running the command below before launching rviz2.

export LANG=en_US.UTF-8

If you don't have that locale installed, follow the instructions in https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html#set-locale

**Comment by benbongalon** [comment]
Haven't heard back so closing.
