### ISSUE TITLE
RosBag with this tutorial

### ISSUE THREAD

**Issue by gsion1** [benbongalon/ros2-urdf-tutorial#5]
Hi, 
I'm trying to understand the tutorial and to replay what state_publisher.py do
What I did (in this order) : 
`rviz2 -d ~/dev_ws/install/urdf_tutorial/share/urdf_tutorial/r2d2.rviz`
In a second terminal
`ros2 bag record -o test1 /tf /tf_static /joint_state`

`ros2 launch urdf_tutorial demo.launch.py`
Wait several seconds and quit record

`ros2 bag play test1`

But nothing happen in rviz, the robot is not replaying what have been recorded 
I think there is an issue with broadcasting or something like that but I found nothing helpful 
I would like to know on which topic I can manually publish to make this robot move, and how to find this topic 
I tried to echo /tf, /tf_static, /joint_state topics, there is a lot of data but I guess there is something missing to make it works

Could you explain how to go a little deeper in this tutorial please ? 
Thanks a lot, 
GS

**Comment by benbongalon** [comment]
Hi GS,

ros2 bag will not do anything for this demo because the robot doesn't receive any input messages (eg, /cmd_vel) to drive it. Instead the motion and pose are self-programmed and internally computed as a function of 4 variable: angle, tilt, height and swivel. See Lines 54-73 of [state_publisher.py](https://github.com/benbongalon/ros2-urdf-tutorial/blob/master/urdf_tutorial/urdf_tutorial/state_publisher.py). So there is nothing for ros2 bag to capture and replay.  Hope that helps.

Ben

**Comment by gsion1** [comment]
Thanks a lot for your help, 
I thought that `self.joint_pub.publish(joint_state)` was responsible of the movement
